import { ApolloClient, InMemoryCache, useQuery } from "@apollo/client";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { query } from "../graphql-queries/query/GET_ALL_POSTS.js";
import Link from "next/link";

export default function Home() {
  const { loading, error, data } = useQuery(query, {
    variables: {
      options: {
        paginate: {
          page: 1,
          limit: 5,
        },
      },
    },
    ssr: true,
    fetchPolicy: "cache-and-network",
  });
  console.log(data);
  if (loading && !data) return <p>Loading ...</p>;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2 className={styles.title}>Welcome to GNext App</h2>

        <div>
          {data.posts.data.map((post, ind) => (
            <Link href={`/post/${post.id}`} key={ind}>
              <p>{post.title}</p>
            </Link>
          ))}
        </div>
      </main>
    </div>
  );
}
